config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'about', to: 'pages#apropos', as: :apropos

  # get 'contact', to: 'pages#contact',  as: :contact
  get 'realisations', to: 'pages#realisation',  as: :realisations

  get 'sitemap.xml', to: 'pages#sitemap'

  resources :articles
  resources :contacts, only: [ :new, :create ]
  # get 'contact', to: 'contacts#new', as: 'contact'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user, optional: true
  # has_many :images, :dependent => :destroy
  validates :titre, presence: true
  validates :description, presence: true

  # validates :photo, presence: true
  mount_uploader :photo, PhotoUploader

private

  def article_params
    params.require(:article).permit(:titre, :description, :genre, :photo)
  end

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name, :validate => true
  attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :phone, :validate => true
  attribute :objet, :validate => true
  attribute :message, :validate => true
  attribute :nickname, :captcha  => true




  # include ActiveModel::Model
  # include ActiveModel::Conversion
  # include ActiveModel::Validations

  # attr_accessor :name, :email, :objet, :message, :phone

  # validates :name, presence: true
  # validates :email, presence: true
  # # ,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  # validates :phone, presence: true
  # validates :objet, presence: true
  # validates :message, presence: true
  # validates :file,      :attachment => true
  # validates :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "d.rolland@ymail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/flat.rb
class Flat < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :article

  mount_uploader :photo, PhotoUploader
  # has_attached_file :photo, :styles => { :large => "960x640>", :medium => "300x300>", :thumb => "150x150>" }, :storage => :cloudinary

end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email, presence: true
  validates :email, uniqueness: true

  has_many :articles

  def name
    "#{prenom} #{nom.upcase}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def confirmation
    authorize Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    # @contact.request = request
      if @contact.valid?
        ContactMailer.new_contact(@contact).deliver
        flash.now[:error] = nil
      else
        flash.now[:error] = "Le message n'a pas pu être envoyé"
        render 'new'
      end

  end
  private

  # def message_params
  #   params.require(:contact).permit(:name, :email, :objet, :message, :phone)
  # end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def apropos
    @articles = Article.all
    @contact = Contact.new
  end
  def home
    @articles = Article.all
    @contact = Contact.new
  end
  def realisation
    @contact = Contact.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/_contact_form.html.erb
<%= simple_form_for(@contact) do |f| %>
  <%= f.input :name, placeholder: "Nom", label: false, :wrapper_html => { :class => 'small-width-input' } %>
  <%= f.input :email, placeholder: "Email", label: false, :wrapper_html => { :class => 'small-width-input' } %>
  <%= f.input :phone, placeholder: "Téléphone", label: false, :wrapper_html => { :class => 'small-width-input' }  %>
  <%= f.input :objet, placeholder: "Nature de prise de contact", as: :select , collection: [ "Demande de devis", "Nous connaitre", "Prise de contact", "Autre"], label: false, :wrapper_html => { :class => 'small-width-input lastchild' } %>
  <%= f.input :message, as: :text, :input_html => { :style => 'width: 100%', :rows => 3 }, placeholder: "Message", label: false, :wrapper_html => { :class => 'large-width-input' }  %>
  <div class="hidden">
    <%= f.label :nickname %>
    <%= f.input :nickname, hint: 'leave this fiel blank' %>
  </div>
  <%= f.submit "Envoyer", class: "btn btn-primary btn-exercise btn-exercise-important"%>
<% end %>

app/views/contacts/_flash.html.erb
<% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>

app/views/contacts/confirmation.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 sign-up">
      <h2>Your message has been sent</h2>
      <p>We will provide you an answer in a short delay</p>
    </div>
  </div>
</div>

app/views/contacts/create.html.erb
<div class="banner-apropos" style="background-image:linear-gradient(-225deg, rgba(89, 92, 93, 0.15) 0%, rgba(40, 42, 44, 0.28) 50%), url('/assets/Tracteur_profil');">
    <h1>CONTACT</h1>
</div>
<div class="moyen-contact">
  <div class="form-contact" align="center">
    <div class="titre-contact-form">
      <h3>N'hesitez pas à nous contacter</h3>
      <hr>
    </div>
    <div id="contact">
      <h1>Merci pour votre message</h1>
    </div>

  </div>
  <hr>
  <div class="contact-dmva">
    <h3>Contactez nous</h3>
    <div class="info-contact">
      <p><strong>ADRESSE:</strong><br> DMVA TP<br>786 rue frédéric Kulhmann<br> 60240 RIEUX FRANCE</p>
    </div>
    <div class="info-contact">
      <p><strong>COORDONNÉES:</strong> <br> 03.44.66.51.02 <br>dmva@orange.fr </p>
    </div>
  </div>
</div>








<div id="map"></div>

app/views/contacts/create.js.erb
// Test for ajax success
console.log("This is the create.js.erb file");
// Render flash message
$('.contact').html("<%= j render 'contact_form' %>");
$('#flash-message').html("<%= j render 'flash' %>").delay(3000).fadeOut(4000);

app/views/contacts/new.html.erb
<%= render 'shared/modal' %>
<div class="banner-apropos" style="background-image:linear-gradient(-225deg, rgba(89, 92, 93, 0.15) 0%, rgba(40, 42, 44, 0.28) 50%), url('/assets/Tracteur_profil');">
    <h1>Contact</h1>
</div>
<div id="contact" class="moyen-contact">
  <div class="form-contact" align="center">
    <div class="titre-contact-form">
      <h3>Envoyez-nous un message</h3>
      <hr class="hidden-xs">
    </div>
    <div class="contact">
      <%= render 'contact_form' %>
    </div>

  </div>
  <hr class="hidden-xs hidden-sm">
  <div class="contact-dmva">
    <h3>Contactez nous</h3>
    <div class="infos-dmva">
      <div class="info-contact">
        <p><strong>ADRESSE:</strong><br> DMVA TP<br>786 rue frédéric Kulhmann<br> 60240 RIEUX FRANCE</p>
      </div>
      <div class="info-contact">
        <p><strong>COORDONNÉES:</strong><br> <a href="tel:0344665102"> 03.44.66.51.02</a><br><a href="mailto:dmvafrancoise@orange.fr"> dmva@orange.fr </a></p>
      </div>
    </div>
  </div>
</div>








<div id="map"></div>

app/views/pages/apropos.html.erb
<%= render 'shared/modal' %>
<div class="banner-apropos" style="background-image:linear-gradient(-225deg, rgba(89, 92, 93, 0.15) 0%, rgba(40, 42, 44, 0.28) 50%), url('/assets/Tracteur_profil');">
    <h1>À Propos</h1>
</div>

<div class="container-home">

  <div id="habilitation" class="services-home">
    <div class="service row">
      <div class="description-service padding-left-des col-xs-12 col-sm-6">
        <hr class="separation sep-horizontal" />
        <h4 class="souligne">L'entreprise</h4>
        <span class="more">
          DMVA est une entreprise de Travaux publics créée en 2003, et opérant dans toute la région de Picardie. DMVA est spécialisée dans 7 domaines : les travaux de voirie, l'assainissement, le terrassement, les réseaux secs, l'eau potable, la maçonnerie industrielle et la démolition. Ensemble nous améliorons notre cadre de vie. Aujourd'hui ils sont 15 à œuvrer à l'aménagement des territoires et à la construction d'infrastructures permettant d'améliorer le cadre de vie des habitants.
        </span>
      </div>
      <%= image_tag 'entreprise', class:"col-xs-12 col-sm-6 picture-service" %>
    </div>


    <div class="service row inverse-flex">
      <%= image_tag 'Ouvrier_a_genoux', class:"col-xs-12 col-sm-6 picture-service padding-right-img" %>
      <div class="description-service padding-right-des col-xs-12 col-sm-6">
        <hr class="separation sep-centrale" />
        <h4>Nos habilitations</h4>
        <span class="more">
        DMVA est habilitée selon le référentiel de management UIC (Union des Industries Chimiques), nous intervenons régulièrement sur des sites chimiques classés en seuil haut (SEVESO 2). Cette habilitation que nous détenons depuis (date) a été renouvelée jusqu'au (date). Nous sommes habilités par un grand nombre de syndicats d'eau et d'assainissement pour intervenir sur leurs réseaux (raccordement tout-à-l'égout, raccordement eau potable).
        </span>
      </div>
    </div>

  </div>


  <div id="infrastructure" class="infrastructures hidden-xs hidden-sm" style="background-image:linear-gradient(-225deg, rgba(89, 92, 93, 0.75) 0%, rgba(40, 42, 44, 0.75) 95%), url('/assets/Tracteur_profil');">
    <%= image_tag 'DMVA - logo blanc-02' %>
    <div class="infrastructures-text">
      <p>Découvrez l'ensemble de nos infrastructures</p>
      <!-- <a href="/assets/Bulldozer.mp4" target="_blank" onclick="revealVideo('video','youtube')">Voir la vidéo >></a> -->
      <button id="playme" onclick="revealVideo('video','youtube')"><p>Voir la vidéo</p></button>
    </div>
        <div id="video" class="lightbox" onclick="hideVideo('video','youtube')">
          <div class="lightbox-container">
            <div class="lightbox-content">

              <button onclick="hideVideo('video','youtube')" class="lightbox-close">
                Close | ✕
              </button>
              <div class="video-container">
                <iframe id="youtube" width="960" height="540" src="https://www.youtube.com/embed/WsptdUFthWI?showinfo=0" frameborder="0" allowfullscreen></iframe>
              </div>

            </div>
          </div>
        </div>
  </div>


  <!-- hover vidéo -->











    <div class="infrastructures-xs hidden-lg hidden-md" style="background-image:linear-gradient(-225deg, rgba(89, 92, 93, 0.75) 0%, rgba(40, 42, 44, 0.75) 95%), url('/assets/Tracteur_profil');">
        <div class="infrastructures-text">
          <p>Découvrez l'ensemble de nos infrastructures</p>
          <a href="http://localhost;3000/assets/Bulldozer.mp4" target="_blank">Voir la vidéo ></a>
        </div>
    </div>




    <div class="lequipe">
      <h2>Notre Equipe</h2>
      <p class="lequipe-description">En plus de notre équipe de 15 salariés, chaque année, nous accueillons stagiaires et jeunes en contrat d'apprentissage, qui viennent consolider avec nous leurs formations.</p>


        <%= render 'shared/team' %>


    </div>

  <div class="travaillons-ensemble">
    <p>Vous souhaitez faire appel à nous ?</p>
    <p><strong>Alors <%= link_to 'travaillons-ensemble', new_contact_path %></strong></p>
  </div>
</div>

app/views/pages/home.html.erb
<%= render 'shared/modal' %>
  <div class="banner" style="background-image:linear-gradient(-225deg, rgba(89, 92, 93, 0.30) 0%, rgba(40, 42, 44, 0.40) 50%), url('<%= cl_image_path 'banner_sa20em' %>');">
    <div class="banner-content">
      <h1><strong>DMVA</strong><br> Travaux Publics</h1>
      <p class="hidden-xs">Située dans l'<strong>oise</strong>, DMVA est une entreprise de <strong>travaux publics</strong> spécialisée dans les travaux de <strong>voirie</strong>, d'<strong>assainissement</strong>, de <strong>terrassement</strong>, de <strong>réseaux secs</strong>, d'eau potable, de <strong>maçonnerie industrielle</strong> et de <strong>démolition</strong>.</p>
      <p class="hidden-lg hidden-md">Spécialiste dans les travaux de voirie, d'assainissement, de terrassement et de maçonnerie industrielle</p>
      <a href="/#actions" class="btn btn-primary btn-lg margin-top-btn">EN SAVOIR +</a>
    </div>
  </div>

<div class="container-home">

  <div id="actions">
    <div class="trois-actions">
    <div class="col-xs-12 col-sm-4 action">
      <div class="icon-position">
        <div class="position-left">
          <%= cl_image_tag 'hand-shake_1_vixpdh', :width=>50 %>
        </div>
        <div class="position-right">
          <h3>Rencontre client</h3>
        </div>
      </div>
      <div class="text-action">
        <div class="position-left">
        <h2>1</h2>
        </div>
        <div class="position-right">
          <p>Nous prenons contact avec vous par téléphone et fixons ensemble un premier rendez vous sur le lieux du futur chantier, l'occasion de discuter de votre projet et de réaliser la prise de mesure.</p>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-4 action">
      <div class="icon-position">
        <div class="position-left">
          <%= cl_image_tag 'note_wvaruy', :height=>50 %>
        </div>
        <div class="position-right">
          <h3>Chiffrage du devis</h3>
        </div>
      </div>
      <div class="text-action">
        <div class="position-left">
          <h2>2</h2>
        </div>
        <div class="position-right">
          <p>La semaine suivant notre rencontre, notre équipe étudiera la meilleure solution possible pour la réalisation de votre projet. Par la suite nous vous ferons parvenir un devis détaillé de notre prestation, avec le montant des travaux.</p>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-4 action">
      <div class="icon-position">
        <div class="position-left">
          <%= cl_image_tag 'helmet_1_ke3eks', :height=>50 %>
        </div>
        <div class="position-right">
          <h3>Réalisation des travaux</h3>
        </div>
      </div>
      <div class="text-action">
        <div class="position-left">
          <h2>3</h2>
        </div>
        <div class="position-right">
         <p>Suite à votre accord concernant les modalités du devis nous vous tenons informé de l'avancé des travaux grâce à un interlocuteur unique, qui reste à votre écoute, du commencement, à la livraison du chantier.</p>
        </div>
      </div>
    </div>
    </div>
    <div class="separation-actions"><hr></div>
  </div>



  <div id="services" class=" services-home">
    <h2>Nos Services</h2>
    <div class="service row inverse-flex">
      <%= cl_image_tag 'workers-535533_1920_conxuq', class:"col-xs-12 col-sm-6 picture-service" %>
      <div class="description-service col-xs-12 col-sm-6">
        <h4>Assainissement</h4>
        <span class="more">
          L'assainissement regroupe l'ensemble des techniques visant à traiter les eaux usées. Ce service des eaux englobe ainsi la pose de réseaux d'évacuation des eaux usées et des eaux de pluie. DMVA propose ainsi la pose de ces réseaux qu'ils soient collectifs ou non mais également la réparation de ces derniers.
          En matière d'eaux usées, DMVA peut ainsi prendre en charge la pose de poste de refoulement, de bacs dégraisseurs ou encore de micro-stations.

          En ce qui concerne les eaux pluviales, nous nous chargerons de la réalisation de vos puisards, de vos drainages, de  vos bassins et fossés ainsi que leurs curages.
        </span>
        <hr class="separation sep-right" />

      </div>
    </div>


    <div class="service row">
      <div class="description-service padding-left-des col-xs-12 col-sm-6">
        <hr class="separation sep-horizontal" />
        <h4>Voirie</h4>
        <span class="more">
          Notre service de voirie vous permettra de faire construire l'ensemble des voies de circulations que vous souhaitez. Qu'il s'agisse d'une autoroute, d'une route, d'une rue, d'un chemin ou même d'une entrée de parking, nous sommes prêt à la réaliser pour vous.

          Ainsi nous intervenons aussi bien sur voie publique et privée et maîtrisons de multiples techniques telles que l'enrochement, le pavage, le terrassement, l'enrobé à chaud ou encore le béton lavé.
        </span>
      </div>
      <%= cl_image_tag 'voirie2_k4tjuc', class:"col-xs-12 col-sm-6 picture-service" %>
    </div>


    <div class="service row inverse-flex service-maconnerie">
      <%= cl_image_tag 'construction-worker-569149_1920_pt3v69', class:"col-xs-12 col-sm-6 picture-service padding-right-img" %>
      <div class="description-service padding-right-des col-xs-12 col-sm-6">
        <hr class="separation sep-centrale" />
        <h4>Maçonnerie</h4>
        <span class="more">
        Notre service de maçonnerie vous permettra de bâtir l'ensemble des constructions que vous souhaitez ! Notre expertise en génie civil nous permet de maîtriser l'ensemble des techniques de constructions, aussi bien la pose de dalle en béton, la pose de parpaings (parpaing creux ou parpaing plein) ou encore la fabrication de murets de soutènements.
        </span>
      </div>
      <%= link_to realisations_path, class:"link-realisation hidden-xs" do %>
        <h3>Voir nos réalisations</h3>
        <%= image_tag 'right-arrow', style:"height: 40px" %>
      <% end %>
    </div>

  </div>


  <div class="brochure" style="background-image:linear-gradient(-225deg, rgba(89, 92, 93, 0.75) 95%, rgba(40, 42, 44, 0.75) 95%), url('/assets/Tracteur_profil');">
      <div class="brochure-text">
        <h3 class="hidden-xs"> Venez découvrir nos services, ainsi que nos réalisations dans notre brochure</h3>
        <a href="/assets/Bulldozer.mp4" target="_blank" class="btn btn-primary btn-lg">Télecharger <br>notre brochure</a>
      </div>
  </div>



  <div class="accomplit-home">
    <h2 class="margin-left-titre">Ce que nous avons accomplit</h2>

    <div class="row accomplit" style="margin-bottom: 6%;"  id="counter">
        <div class="desc-bloc-accompli col-md-10 col-xs-12">
          <p class="hidden-xs">Chaque jour nos équipes se mettent en mouvement, pour construire, développer et préserver notre environnement. Depuis plus de 15 ans, nous faisons en sorte que cette "machine" fonctionne, cela passe notamment par la rigueur, l'organisation mais aussi par la passion que nos employés et collaborateurs tentent de transmettre à nos clients, afin de proposer une offre unique d'ouvrage et de prestation que se soit des entreprises, des collectivités et des particuliers.</p>

          <!-- <h2 class="visible-xs size-titre">Ce que nous avons accomplit</h2> -->

          <div class="row chiffres-accomplit ">
            <div class="chiffre-accomplit col-xs-12 col-md-2">
              <div class="counter-value text-center" data-count="2000">0</div>
              <h4>Projets</h4>
            </div>
            <div class="chiffre-accomplit col-xs-12 col-md-2">
              <div class="counter-value text-center" data-count="250">0</div>
              <h4>Clients</h4>
            </div>
            <div class="chiffre-accomplit col-xs-12 col-md-2">
              <div class="counter-value text-center" data-count="15">0</div>
              <h4>Employés</h4>
            </div>
            <div class="chiffre-accomplit col-xs-12 col-md-2">
              <div class="counter-value text-center" data-count="7">0</div>
              <h4>Habilitations</h4>
            </div>
            <div class="chiffre-accomplit col-xs-12 col-md-2">
              <div class="counter-value text-center" data-count="15">0</div>
              <h4>Machines</h4>
            </div>
          </div>
        </div>
        <div class="card col-md-2 col-xs-12" style="background-image: linear-gradient(rgba(219, 135, 78, 0.76), rgba(219, 135, 78, 0.76)), url(<%= cl_image_path 'workers-535533_1920_conxuq' %>);">
          <div class="card-description">
            <h3 class="size-h3 counter-value" data-count="40">0</h3>
            <h5>Années d'expérience dans le secteur</h5>
          </div>
        </div>
    </div>

  </div>



  <div id="actualite" class="projets-home lequipe">
    <h2>Nos actualités</h2>

    <%= render 'shared/actualite-dynamique' %>


  </div>

  <div class="partenaire-home">

    <%= render 'shared/partenaire' %>


  </div>

  <div class="travaillons-ensemble marge-top-sanscarsouel">
    <p>Vous souhaitez faire appel à nous ?</p>
    <p><strong>Alors <%= link_to 'travaillons-ensemble', new_contact_path %></strong></p>
  </div>


</div>

app/views/shared/_carousel-parc-materiel.html.erb
    <div id="my-slider3" class="carousel slider multi-item-carousel-4" data-ride="carousel">

      <ol class="carousel-indicators">
        <li data-target="#my-slider3" data-slide-to="0" class="active"></li>
        <li data-target="#my-slider3" data-slide-to="1"></li>
        <li data-target="#my-slider3" data-slide-to="2"></li>
        <li data-target="#my-slider3" data-slide-to="3"></li>
      </ol>


      <div class="carousel-inner" role="listbox">

          <%= render 'shared/parc-materiel' %>

      </div>

      <a class="left carousel-control" href="#my-slider3" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#my-slider3" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>

    </div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-content">
    <div class="footer-contact col-xs-12 col-sm-4">
      <%= cl_image_tag 'Plan-de-travail-1_biqmut', height: 70, width: 70 %>
      <div class="footer-adresse">
        <p>786 rue frédéric Kulhmann</p>
        <p>60240 RIEUX</p>
        <p>FRANCE</p>
      </div>
      <div class="telephone-footer">
        <p><a href="tel:+33344665102"> 03.44.66.51.02</a></p>
        <p><a href="mailto:dmvafrancoise@orange.fr">dmva@orange.fr</a></p>
      </div>
    </div>
    <div class="footer-dmva col-xs-12 col-sm-4 hidden-xs hidden-sm">
      <div class="titre-top-footer">
        <hr>
        <h4>DMVA</h4>
      </div>
      <div class="link-page">
        <p><%= link_to 'Nos services', root_path(anchor: "services") %></p>
        <p><%= link_to 'Notre actualité', root_path(anchor: "actualite") %></p>
        <p><%= link_to 'Nos infrastructures', apropos_path(anchor: "infrastructure") %></p>
        <p><%= link_to 'Nos habilitations', apropos_path(anchor: "habilitation") %></p>
        <p><%= link_to 'Nos réalisations', realisations_path(anchor: "realisation") %></p>
        <p><%= link_to 'Notre matériel', realisations_path(anchor: "materiel") %></p>
        <p><%= link_to 'Nous contacter', new_contact_path(anchor: "contact") %></p>
      </div>
    </div>
    <div class="footer-informations col-xs-12 col-sm-4">
      <div class="titre-top-footer">
        <hr>
        <h4>INFORMATIONS</h4>
      </div>
      <p>Située dans l'oise, DMVA est une entreprise de travaux publics spécialisée dans les travaux de voirie, d'assainissement, de terrassement, de réseaux secs, d'eau potable, de maçonnerie industrielle et de démolition.</p>
      <h5>Lundi - Vendredi: 08:00 - 17:00</h5>
      <h5>Samedi & Dimanche: fermé</h5>
    </div>
  </div>
  <div class="footer-bas">
    <div class="footer-links col-xs-12 col-sm-4">
      <a href="https://www.facebook.com/dmvaTP/?ref=bookmarks" target="_blank"><i class="fa fa-facebook"></i></a>
      <a href="#" target="_blank"><i class="fa fa-google"></i></a>
      <a href="https://www.linkedin.com/company/dmva" target="_blank"><i class="fa fa-linkedin"></i></a>
    </div>
    <div class="footer-copyright col-xs-12 col-sm-4 hidden-xs">
      <a href="http://www.avemcreation.com/" target="_blank">
      DMVA Travaux publics. Conçu par Avem Creation</a>
    </div>
    <div class="back-up col-xs-12 col-sm-4">
      <%= link_to 'Retour en haut  ' %><i class="fa fa-level-up" aria-hidden="true"></i>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <!-- Logo -->
  <% if user_signed_in? %>
    <%= link_to 'A', admin_dashboard_path, class:"btn btn-primary btn-lg margin-top-btn top-left" %>
  <% end %>
  <%= link_to root_path do %>
    <img src="/assets/DMVA.png" alt="" style="height: 50px">
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-right hidden-xs hidden-sm">
    <div class="link">

      <%= link_to 'ACCUEIL', root_path, :class => "navbar-item navbar-link" %>
      <%= link_to 'A PROPOS', apropos_path, :class => "navbar-item navbar-link" %>
      <%= link_to 'REALISATIONS', realisations_path, :class => "navbar-item navbar-link" %>
      <%= link_to 'CONTACT', new_contact_path, :class => "navbar-item navbar-link" %>

    </div>
    <div class="contact-navbar">
      <a href="tel:+33344665102" class="navbar-item font-contact"><i class="fa fa-phone" aria-hidden="true"></i> 03 44 66 51 02</a>
      <div class="dropdown">
        <a href="" data-toggle="dropdown" class="navbar-item font-contact"><i class="fa fa-clock-o" aria-hidden="true"></i> 08:00 - 17:00</a>
        <ul class="dropdown-menu dropdown-menu-right navbar-dropdown-menu">
          <li><a href="#">Lundi - Vendredi 08:00 - 17:00</a></li>
          <li><a href="#">Samedi - Dimanche fermé</a></li>
        </ul>
      </div>
    </div>
  </div>


  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-dropdown-menu">
        <li><%= link_to 'Acceuil', root_path %></li>
        <li><%= link_to 'A Propos', apropos_path %></li>
        <li><%= link_to 'Réalisations', realisations_path %></li>
        <li><%= link_to 'Contact', new_contact_path %></li>
      </ul>
    </div>
  </div>

  <div id="myBtn" class="demande-devis hidden-xs">DEMANDER UN DEVIS</div>
</div>